/*
 * generated by Xtext
 */
package org.larz.dom3.dm.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DmExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.larz.dom3.dm.ui.internal.DmActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.larz.dom3.dm.ui.internal.DmActivator.getInstance().getInjector("org.larz.dom3.dm.Dm");
	}
	
}
