/*
* generated by Xtext
*/
package org.larz.dom3.dm.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.larz.dom3.dm.services.DmGrammarAccess;

public class DmParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DmGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_ML_COMMENT", "RULE_SL_COMMENT", "RULE_WS");
	}
	
	@Override
	protected org.larz.dom3.dm.parser.antlr.internal.InternalDmParser createParser(XtextTokenStream stream) {
		return new org.larz.dom3.dm.parser.antlr.internal.InternalDmParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Dom3Mod";
	}
	
	public DmGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DmGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
